<?php


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //  $countries = factory(CountryCms::class, 10)->create();

        $countries = array(
            array(
                'id' => 1,
                'name' => 'China',
                'calling_code' => '86',
                'capital' => 'Beijing',
                'code' => 'cn',
                'code_alpha3' => 'chn',
                'currency_code' => 'CNY',
                'currency_name' => 'Yuan Renminbi',
                'emoji' => '🇨🇳',
                'full_name' => 'Peoples Republic of China',
                'top_level_domain' => '.cn',
            ),
            array(
                'id' => 2,
                'name' => 'India',
                'calling_code' => '91',
                'capital' => 'New Delhi',
                'code' => 'in',
                'code_alpha3' => 'ind',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'emoji' => '🇮🇳',
                'full_name' => 'The Republic of India',
                'top_level_domain' => '.in',
            ),
            array(
                'id' => 3,
                'name' => 'United States',
                'calling_code' => '1',
                'capital' => 'Washington D.C.',
                'code' => 'us',
                'code_alpha3' => 'usa',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇺🇸',
                'full_name' => 'The United States of America',
                'top_level_domain' => '.us',
            ),
            array(
                'id' => 4,
                'name' => 'Indonesia',
                'calling_code' => '62',
                'capital' => 'Jakarta',
                'code' => 'id',
                'code_alpha3' => 'idn',
                'currency_code' => 'IDR',
                'currency_name' => 'Rupiah',
                'emoji' => '🇮🇩',
                'full_name' => 'The Republic of Indonesia',
                'top_level_domain' => '.id',
            ),
            array(
                'id' => 5,
                'name' => 'Brazil',
                'calling_code' => '55',
                'capital' => 'Brasília',
                'code' => 'br',
                'code_alpha3' => 'bra',
                'currency_code' => 'BRL',
                'currency_name' => 'Brazilian Real',
                'emoji' => '🇧🇷',
                'full_name' => 'The Federative Republic of Brazil',
                'top_level_domain' => '.br',
            ),
            array(
                'id' => 6,
                'name' => 'Pakistan',
                'calling_code' => '92',
                'capital' => 'Islamabad',
                'code' => 'pk',
                'code_alpha3' => 'pak',
                'currency_code' => 'PKR',
                'currency_name' => 'Pakistan Rupee',
                'emoji' => '🇵🇰',
                'full_name' => 'The Islamic Republic of Pakistan',
                'top_level_domain' => '.pk',
            ),
            array(
                'id' => 7,
                'name' => 'Nigeria',
                'calling_code' => '234',
                'capital' => 'Abuja',
                'code' => 'ng',
                'code_alpha3' => 'nga',
                'currency_code' => 'NGN',
                'currency_name' => 'Naira',
                'emoji' => '🇳🇬',
                'full_name' => 'Federal Republic of Nigeria',
                'top_level_domain' => '.ng',
            ),
            array(
                'id' => 8,
                'name' => 'Bangladesh',
                'calling_code' => '880',
                'capital' => 'Dhaka',
                'code' => 'bd',
                'code_alpha3' => 'bgd',
                'currency_code' => 'BDT',
                'currency_name' => 'Taka',
                'emoji' => '🇧🇩',
                'full_name' => 'Peoples Republic of Bangladesh',
                'top_level_domain' => '.bd',
            ),
            array(
                'id' => 9,
                'name' => 'Russia',
                'calling_code' => '7',
                'capital' => 'Moscow',
                'code' => 'ru',
                'code_alpha3' => 'rus',
                'currency_code' => 'RUB',
                'currency_name' => 'Russian Ruble',
                'emoji' => '🇷🇺',
                'full_name' => 'Russian Federation',
                'top_level_domain' => '.ru',
            ),
            array(
                'id' => 10,
                'name' => 'Mexico',
                'calling_code' => '52',
                'capital' => 'Mexico CityCms',
                'code' => 'mx',
                'code_alpha3' => 'mex',
                'currency_code' => 'MXN',
                'currency_name' => 'Mexican Peso',
                'emoji' => '🇲🇽',
                'full_name' => 'The United States of Mexico',
                'top_level_domain' => '.mx',
            ),
            array(
                'id' => 11,
                'name' => 'Japan',
                'calling_code' => '81',
                'capital' => 'Tokyo',
                'code' => 'jp',
                'code_alpha3' => 'jpn',
                'currency_code' => 'JPY',
                'currency_name' => 'Yen',
                'emoji' => '🇯🇵',
                'full_name' => 'Japan',
                'top_level_domain' => '.jp',
            ),
            array(
                'id' => 12,
                'name' => 'Ethiopia',
                'calling_code' => '251',
                'capital' => 'Addis Ababa',
                'code' => 'et',
                'code_alpha3' => 'eth',
                'currency_code' => 'ETB',
                'currency_name' => 'Ethiopian Birr',
                'emoji' => '🇪🇹',
                'full_name' => 'The Federal Democratic Republic of Ethiopia',
                'top_level_domain' => '.et',
            ),
            array(
                'id' => 13,
                'name' => 'Philippines',
                'calling_code' => '63',
                'capital' => 'Manila',
                'code' => 'ph',
                'code_alpha3' => 'phl',
                'currency_code' => 'PHP',
                'currency_name' => 'Philippine Peso',
                'emoji' => '🇵🇭',
                'full_name' => 'Republic of the Philippines',
                'top_level_domain' => '.ph',
            ),
            array(
                'id' => 14,
                'name' => 'Egypt',
                'calling_code' => '20',
                'capital' => 'Cairo',
                'code' => 'eg',
                'code_alpha3' => 'egy',
                'currency_code' => 'EGP',
                'currency_name' => 'Egyptian Pound',
                'emoji' => '🇪🇬',
                'full_name' => 'the Arab Republic of Egypt ',
                'top_level_domain' => '.eg',
            ),
            array(
                'id' => 15,
                'name' => 'Vietnam',
                'calling_code' => '84',
                'capital' => 'Hanoi',
                'code' => 'vn',
                'code_alpha3' => 'vnm',
                'currency_code' => 'VND',
                'currency_name' => 'Dong',
                'emoji' => '🇻🇳',
                'full_name' => 'Socialist Republic of Vietnam',
                'top_level_domain' => '.vn',
            ),
            array(
                'id' => 16,
                'name' => 'DR Congo',
                'calling_code' => '243',
                'capital' => 'Kinshasa',
                'code' => 'cd',
                'code_alpha3' => 'cod',
                'currency_code' => 'CDF',
                'currency_name' => 'Congolese franc',
                'emoji' => '🇨🇩',
                'full_name' => 'Democratic Republic of the Congo',
                'top_level_domain' => '.cd',
            ),
            array(
                'id' => 17,
                'name' => 'Turkey',
                'calling_code' => '90',
                'capital' => 'Ankara',
                'code' => 'tr',
                'code_alpha3' => 'tur',
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish Lira',
                'emoji' => '🇹🇷',
                'full_name' => 'The Republic of Turkey',
                'top_level_domain' => '.tr',
            ),
            array(
                'id' => 18,
                'name' => 'Iran',
                'calling_code' => '98',
                'capital' => 'Tehran',
                'code' => 'ir',
                'code_alpha3' => 'irn',
                'currency_code' => 'IRR',
                'currency_name' => 'Iranian rial',
                'emoji' => '🇮🇷',
                'full_name' => 'The Islamic Republic of Iran',
                'top_level_domain' => '.ir',
            ),
            array(
                'id' => 19,
                'name' => 'Germany',
                'calling_code' => '49',
                'capital' => 'Berlin',
                'code' => 'de',
                'code_alpha3' => 'deu',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇩🇪',
                'full_name' => 'The Federal Republic of Germany',
                'top_level_domain' => '.de',
            ),
            array(
                'id' => 20,
                'name' => 'Thailand',
                'calling_code' => '66',
                'capital' => 'Bangkok',
                'code' => 'th',
                'code_alpha3' => 'tha',
                'currency_code' => 'THB',
                'currency_name' => 'Baht',
                'emoji' => '🇹🇭',
                'full_name' => 'Kingdom of Thailand',
                'top_level_domain' => '.th',
            ),
            array(
                'id' => 21,
                'name' => 'United Kingdom',
                'calling_code' => '44',
                'capital' => 'London',
                'code' => 'gb',
                'code_alpha3' => 'eng',
                'currency_code' => 'GBP',
                'currency_name' => 'Pound sterling',
                'emoji' => '🇬🇧',
                'full_name' => 'The United Kingdom of Great Britain and Northern Ireland',
                'top_level_domain' => '.uk',
            ),
            array(
                'id' => 22,
                'name' => 'France',
                'calling_code' => '33',
                'capital' => 'Paris',
                'code' => 'fr',
                'code_alpha3' => 'fra',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇫🇷',
                'full_name' => 'The French Republic',
                'top_level_domain' => '.fr',
            ),
            array(
                'id' => 23,
                'name' => 'Tanzania',
                'calling_code' => '255',
                'capital' => 'Dodoma',
                'code' => 'tz',
                'code_alpha3' => 'tza',
                'currency_code' => 'TZS',
                'currency_name' => 'Tanzanian shilling',
                'emoji' => '🇹🇿',
                'full_name' => 'The United Republic of Tanzania',
                'top_level_domain' => '.tz',
            ),
            array(
                'id' => 24,
                'name' => 'Italy',
                'calling_code' => '39',
                'capital' => 'Rome',
                'code' => 'it',
                'code_alpha3' => 'ita',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇮🇹',
                'full_name' => 'The Republic of Italy',
                'top_level_domain' => '.it',
            ),
            array(
                'id' => 25,
                'name' => 'South Africa',
                'calling_code' => '27',
                'capital' => 'Pretoria',
                'code' => 'za',
                'code_alpha3' => 'zaf',
                'currency_code' => 'ZAR',
                'currency_name' => 'Rand',
                'emoji' => '🇿🇦',
                'full_name' => 'The Republic of South Africa',
                'top_level_domain' => '.za',
            ),
            array(
                'id' => 26,
                'name' => 'Myanmar',
                'calling_code' => '95',
                'capital' => 'Naypyidaw',
                'code' => 'mm',
                'code_alpha3' => 'mmr',
                'currency_code' => 'MMK',
                'currency_name' => 'Kyat',
                'emoji' => '🇲🇲',
                'full_name' => 'Republic Of The Union Of Myanmar',
                'top_level_domain' => '.mm',
            ),
            array(

                'id' => 27,
                'name' => 'Kenya',
                'calling_code' => '254',
                'capital' => 'Nairobi',
                'code' => 'ke',
                'code_alpha3' => 'ken',
                'currency_code' => 'KES',
                'currency_name' => 'Kenyan Shilling',
                'emoji' => '🇰🇪',
                'full_name' => 'The Republic of Kenya',
                'top_level_domain' => '.ke',
            ),
            array(
                'id' => 28,
                'name' => 'Korea',
                'calling_code' => '82',
                'capital' => 'Seoul',
                'code' => 'kr',
                'code_alpha3' => 'kor',
                'currency_code' => 'KRW',
                'currency_name' => 'South Korean won',
                'emoji' => '🇰🇷',
                'full_name' => 'Republic of Korea',
                'top_level_domain' => '.kr',
            ),
            array(
                'id' => 29,
                'name' => 'Colombia',
                'calling_code' => '57',
                'capital' => 'Bogotá',
                'code' => 'co',
                'code_alpha3' => 'col',
                'currency_code' => 'COP',
                'currency_name' => 'Colombian Peso',
                'emoji' => '🇨🇴',
                'full_name' => 'The Republic of Colombia',
                'top_level_domain' => '.co',
            ),
            array(
                'id' => 30,
                'name' => 'Spain',
                'calling_code' => '34',
                'capital' => 'Madrid',
                'code' => 'es',
                'code_alpha3' => 'esp',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇪🇸',
                'full_name' => 'The Kingdom of Spain',
                'top_level_domain' => '.es',
            ),
            array(
                'id' => 31,
                'name' => 'Uganda',
                'calling_code' => '256',
                'capital' => 'Kampala',
                'code' => 'ug',
                'code_alpha3' => 'uga',
                'currency_code' => 'UGX',
                'currency_name' => 'Uganda Shilling',
                'emoji' => '🇺🇬',
                'full_name' => 'The Republic of Uganda',
                'top_level_domain' => '.ug',
            ),
            array(
                'id' => 32,
                'name' => 'Argentina',
                'calling_code' => '54',
                'capital' => 'Buenos Aires',
                'code' => 'ar',
                'code_alpha3' => 'arg',
                'currency_code' => 'ARS',
                'currency_name' => 'Argentine Peso',
                'emoji' => '🇦🇷',
                'full_name' => 'The Republic of Argentina',
                'top_level_domain' => '.ar',
            ),
            array(
                'id' => 33,
                'name' => 'Ukraine',
                'calling_code' => '380',
                'capital' => 'Kyiv',
                'code' => 'ua',
                'code_alpha3' => 'ukr',
                'currency_code' => 'UAH',
                'currency_name' => 'Hryvnia',
                'emoji' => '🇺🇦',
                'full_name' => 'Ukraine',
                'top_level_domain' => '.ua',
            ),
            array (
                'id' => 34,
                'name' => 'Algeria',
                'calling_code' => '213',
                'capital' => 'Algiers',
                'code' => 'dz',
                'code_alpha3' => 'dza',
                'currency_code' => 'DZD',
                'currency_name' => 'Algerian Dinar',
                'emoji' => '🇩🇿',
                'full_name' => 'Peoples Democratic Republic of Algeria',
                'top_level_domain' => '.dz',
            ),
            array(
                'id' => 35,
                'name' => 'Sudan',
                'calling_code' => '249',
                'capital' => 'Khartoum',
                'code' => 'sd',
                'code_alpha3' => 'sdn',
                'currency_code' => 'SDG',
                'currency_name' => 'Sudanese Pound',
                'emoji' => '🇸🇩',
                'full_name' => 'The Republic of Sudan',
                'top_level_domain' => '.sd',
            ),
            array(
                'id' => 36,
                'name' => 'Iraq',
                'calling_code' => '964',
                'capital' => 'Baghdad',
                'code' => 'iq',
                'code_alpha3' => 'irq',
                'currency_code' => 'IQD',
                'currency_name' => 'Iraqi Dinar',
                'emoji' => '🇮🇶',
                'full_name' => 'Republic Of Iraq',
                'top_level_domain' => '.iq',
            ),
            array(
                'id' => 37,
                'name' => 'Poland',
                'calling_code' => '48',
                'capital' => 'Warsaw',
                'code' => 'pl',
                'code_alpha3' => 'pol',
                'currency_code' => 'PLN',
                'currency_name' => 'Zloty',
                'emoji' => '🇵🇱',
                'full_name' => 'The Republic of Poland',
                'top_level_domain' => '.pl',
            ),
            array(
                'id' => 38,
                'name' => 'Canada',
                'calling_code' => '1',
                'capital' => 'Ottawa',
                'code' => 'ca',
                'code_alpha3' => 'can',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'emoji' => '🇨🇦',
                'full_name' => 'Canada',
                'top_level_domain' => '.ca',
            ),
            array(
                'id' => 39,
                'name' => 'Afghanistan',
                'calling_code' => '93',
                'capital' => 'Kabul',
                'code' => 'af',
                'code_alpha3' => 'afg',
                'currency_code' => 'AFN',
                'currency_name' => 'Afghani',
                'emoji' => '🇦🇫',
                'full_name' => 'the Islamic Republic of Afghanistan',
                'top_level_domain' => '.af',
            ),
            array(
                'id' => 40,
                'name' => 'Morocco',
                'calling_code' => '212',
                'capital' => 'Rabat',
                'code' => 'ma',
                'code_alpha3' => 'mar',
                'currency_code' => 'MAD',
                'currency_name' => 'Moroccan Dirham',
                'emoji' => '🇲🇦',
                'full_name' => 'The Kingdom of Morocco',
                'top_level_domain' => '.ma',
            ),
            array(
                'id' => 41,
                'name' => 'Saudi Arabia',
                'calling_code' => '966',
                'capital' => 'Riyadh',
                'code' => 'sa',
                'code_alpha3' => 'sau',
                'currency_code' => 'SAR',
                'currency_name' => 'Saudi Riyal',
                'emoji' => '🇸🇦',
                'full_name' => 'Kingdom of Saudi Arabia',
                'top_level_domain' => '.sa',
            ),
            array(
                'id' => 42,
                'name' => 'Peru',
                'calling_code' => '51',
                'capital' => 'Lima',
                'code' => 'pe',
                'code_alpha3' => 'per',
                'currency_code' => 'PEN',
                'currency_name' => 'Nuevo Sol',
                'emoji' => '🇵🇪',
                'full_name' => 'The Republic of Peru',
                'top_level_domain' => '.pe',
            ),
            array(
                'id' => 43,
                'name' => 'Uzbekstan',
                'calling_code' => '998',
                'capital' => 'Tashkent',
                'code' => 'uz',
                'code_alpha3' => 'uzb',
                'currency_code' => 'UZS',
                'currency_name' => 'Uzbekistan Sum',
                'emoji' => '🇺🇿',
                'full_name' => 'The Republic of Uzbekistan',
                'top_level_domain' => '.uz',
            ),
            array(
                'id' => 44,
                'name' => 'Venezuela',
                'calling_code' => '58',
                'capital' => 'Caracas',
                'code' => 've',
                'code_alpha3' => 'ven',
                'currency_code' => 'VEF',
                'currency_name' => 'Venezuelan bolívar',
                'emoji' => '🇻🇪',
                'full_name' => 'Bolivarian Republic of Venezuela',
                'top_level_domain' => '.ve',
            ),
            array(
                'id' => 45,
                'name' => 'Malaysia',
                'calling_code' => '60',
                'capital' => 'Kuala Lumpur',
                'code' => 'my',
                'code_alpha3' => 'mys',
                'currency_code' => 'MYR',
                'currency_name' => 'Malaysian Ringgit',
                'emoji' => '🇲🇾',
                'full_name' => 'Malaysia',
                'top_level_domain' => '.my',
            ),
            array(
                'id' => 46,
                'name' => 'Angola',
                'calling_code' => '244',
                'capital' => 'Luanda',
                'code' => 'ao',
                'code_alpha3' => 'ago',
                'currency_code' => 'AOA',
                'currency_name' => 'Kwanza',
                'emoji' => '🇦🇴',
                'full_name' => 'the Republic of Angola',
                'top_level_domain' => '.ao',
            ),
            array(
                'id' => 47,
                'name' => 'Mozambique',
                'calling_code' => '258',
                'capital' => 'Maputo',
                'code' => 'mz',
                'code_alpha3' => 'moz',
                'currency_code' => 'MZN',
                'currency_name' => 'Mozambique Metical',
                'emoji' => '🇲🇿',
                'full_name' => 'The Republic of Mozambique',
                'top_level_domain' => '.mz',
            ),
            array(
                'id' => 48,
                'name' => 'Ghana',
                'calling_code' => '233',
                'capital' => 'Accra',
                'code' => 'gh',
                'code_alpha3' => 'gha',
                'currency_code' => 'GHS',
                'currency_name' => 'Ghana Cedi',
                'emoji' => '🇬🇭',
                'full_name' => 'The Republic of Ghana',
                'top_level_domain' => '.gh',
            ),
            array(
                'id' => 49,
                'name' => 'Nepal',
                'calling_code' => '977',
                'capital' => 'Kathmandu',
                'code' => 'np',
                'code_alpha3' => 'npl',
                'currency_code' => 'NPR',
                'currency_name' => 'Nepalese Rupee',
                'emoji' => '🇳🇵',
                'full_name' => 'Federal Democratic Republic of Nepal',
                'top_level_domain' => '.np',
            ),
            array(
                'id' => 50,
                'name' => 'Yemen',
                'calling_code' => '967',
                'capital' => 'Sana\'a',
                'code' => 'ye',
                'code_alpha3' => 'yem',
                'currency_code' => 'YER',
                'currency_name' => 'Yemeni Rial',
                'emoji' => '🇾🇪',
                'full_name' => 'The Republic of Yemen',
                'top_level_domain' => '.ye',
            ),
            array(
                'id' => 51,
                'name' => 'Madagascar',
                'calling_code' => '261',
                'capital' => 'Antananarivo',
                'code' => 'mg',
                'code_alpha3' => 'mdg',
                'currency_code' => 'MGA',
                'currency_name' => 'Malagasy Ariary',
                'emoji' => '🇲🇬',
                'full_name' => 'the Republic of Madagascar ',
                'top_level_domain' => '.mg',
            ),
            array(
                'id' => 52,
                'name' => 'Korea,DPR',
                'calling_code' => '850',
                'capital' => 'Pyongyang',
                'code' => 'kp',
                'code_alpha3' => 'prk',
                'currency_code' => 'KPW',
                'currency_name' => 'North Korean won',
                'emoji' => '🇰🇵',
                'full_name' => 'Democratic People\'s Republic of Korea',
                'top_level_domain' => '.kp',
            ),
            array(
                'id' => 53,
                'name' => 'Cote d\'lvoire',
                'calling_code' => '225',
                'capital' => 'Yamoussoukro',
                'code' => 'ci',
                'code_alpha3' => 'civ',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇨🇮',
                'full_name' => 'the Republic of Cote d\'ivoire',
                'top_level_domain' => '.ci',
            ),
            array(
                'id' => 54,
                'name' => 'Cameroon',
                'calling_code' => '237',
                'capital' => 'Yaoundé',
                'code' => 'cm',
                'code_alpha3' => 'cmr',
                'currency_code' => 'XAF',
                'currency_name' => 'CFA Franc BEAC',
                'emoji' => '🇨🇲',
                'full_name' => 'the Republic of Cameroon',
                'top_level_domain' => '.cm',
            ),
            array(
                'id' => 55,
                'name' => 'Australia',
                'calling_code' => '61',
                'capital' => 'Canberra',
                'code' => 'au',
                'code_alpha3' => 'aus',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'emoji' => '🇦🇺',
                'full_name' => 'The Commonwealth of Australia',
                'top_level_domain' => '.au',
            ),
            array(
                'id' => 56,
                'name' => 'Niger',
                'calling_code' => '227',
                'capital' => 'Niamey',
                'code' => 'ne',
                'code_alpha3' => 'ner',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇳🇪',
                'full_name' => 'The Republic of Niger',
                'top_level_domain' => '.ne',
            ),
            array(
                'id' => 57,
                'name' => 'Sri Lanka',
                'calling_code' => '94',
                'capital' => 'Colombo',
                'code' => 'lk',
                'code_alpha3' => 'lka',
                'currency_code' => 'LKR',
                'currency_name' => 'Sri Lanka Rupee',
                'emoji' => '🇱🇰',
                'full_name' => 'The Democratic Socialist Republic of Sri Lanka',
                'top_level_domain' => '.lk',
            ),
            array(
                'id' => 58,
                'name' => 'Burkina Faso',
                'calling_code' => '226',
                'capital' => 'Ouagadougou',
                'code' => 'bf',
                'code_alpha3' => 'bfa',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇧🇫',
                'full_name' => 'Burkina Faso',
                'top_level_domain' => '.bf',
            ),
            array(
                'id' => 59,
                'name' => 'Malawi',
                'calling_code' => '265',
                'capital' => 'Lilongwe',
                'code' => 'mw',
                'code_alpha3' => 'mwi',
                'currency_code' => 'MWK',
                'currency_name' => 'Kwacha',
                'emoji' => '🇲🇼',
                'full_name' => 'The Republic of Malawi',
                'top_level_domain' => '.mw',
            ),
            array(
                'id' => 60,
                'name' => 'Mali',
                'calling_code' => '223',
                'capital' => 'Bamako',
                'code' => 'ml',
                'code_alpha3' => 'mli',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇲🇱',
                'full_name' => 'The Republic of Mali',
                'top_level_domain' => '.ml',
            ),
            array(
                'id' => 61,
                'name' => 'Romania',
                'calling_code' => '40',
                'capital' => 'Bucharest',
                'code' => 'ro',
                'code_alpha3' => 'rom',
                'currency_code' => 'RON',
                'currency_name' => 'New Romanian Leu',
                'emoji' => '🇷🇴',
                'full_name' => 'Romania',
                'top_level_domain' => '.ro',
            ),
            array(
                'id' => 62,
                'name' => 'Kazakhstan',
                'calling_code' => '76',
                'capital' => 'Astana',
                'code' => 'kz',
                'code_alpha3' => 'kaz',
                'currency_code' => 'KZT',
                'currency_name' => 'Tenge',
                'emoji' => '🇰🇿',
                'full_name' => 'The Republic of Kazakhstan',
                'top_level_domain' => '.kz',
            ),
            array(
                'id' => 63,
                'name' => 'Syria',
                'calling_code' => '963',
                'capital' => 'Damascus',
                'code' => 'sy',
                'code_alpha3' => 'syr',
                'currency_code' => 'SYP',
                'currency_name' => 'Syrian Pound',
                'emoji' => '🇸🇾',
                'full_name' => 'The Syrian Arab Republic',
                'top_level_domain' => '.sy',
            ),
            array(
                'id' => 64,
                'name' => 'Chile',
                'calling_code' => '56',
                'capital' => 'Santiago',
                'code' => 'cl',
                'code_alpha3' => 'chl',
                'currency_code' => 'CLP',
                'currency_name' => 'Chilean Peso',
                'emoji' => '🇨🇱',
                'full_name' => 'Republic of Chile',
                'top_level_domain' => '.cl',
            ),
            array(
                'id' => 65,
                'name' => 'Zambia',
                'calling_code' => '260',
                'capital' => 'Lusaka',
                'code' => 'zm',
                'code_alpha3' => 'zmb',
                'currency_code' => 'ZMW',
                'currency_name' => 'Zambian Kwacha',
                'emoji' => '🇿🇲',
                'full_name' => 'The Republic of Zambia',
                'top_level_domain' => '.zm',
            ),
            array(
                'id' => 66,
                'name' => 'Guatemala',
                'calling_code' => '502',
                'capital' => 'Guatemala CityCms',
                'code' => 'gt',
                'code_alpha3' => 'gtm',
                'currency_code' => 'GTQ',
                'currency_name' => 'Quetzal',
                'emoji' => '🇬🇹',
                'full_name' => 'The Republic of Guatemala',
                'top_level_domain' => '.gt',
            ),
            array(
                'id' => 67,
                'name' => 'Zimbabwe',
                'calling_code' => '263',
                'capital' => 'Harare',
                'code' => 'zw',
                'code_alpha3' => 'zwe',
                'currency_code' => 'ZWL',
                'currency_name' => 'Zimbabwe Dollar',
                'emoji' => '🇿🇼',
                'full_name' => 'the Republic of Zimbabwe',
                'top_level_domain' => '.zw',
            ),
            array(
                'id' => 68,
                'name' => 'Netherlands',
                'calling_code' => '31',
                'capital' => 'Amsterdam',
                'code' => 'nl',
                'code_alpha3' => 'nld',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇳🇱',
                'full_name' => 'The Kingdom of Netherlands',
                'top_level_domain' => '.nl',
            ),
            array(
                'id' => 69,
                'name' => 'Ecuador',
                'calling_code' => '593',
                'capital' => 'Quito',
                'code' => 'ec',
                'code_alpha3' => 'ecu',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇪🇨',
                'full_name' => 'The Republic of Ecuador',
                'top_level_domain' => '.ec',
            ),
            array(
                'id' => 70,
                'name' => 'Senegal',
                'calling_code' => '221',
                'capital' => 'Dakar',
                'code' => 'sn',
                'code_alpha3' => 'sen',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇸🇳',
                'full_name' => 'the Republic of Senegal',
                'top_level_domain' => '.sn',
            ),
            array(
                'id' => 71,
                'name' => 'Cambodia',
                'calling_code' => '855',
                'capital' => 'Phnom Penh',
                'code' => 'kh',
                'code_alpha3' => 'khm',
                'currency_code' => 'KHR',
                'currency_name' => 'Riel',
                'emoji' => '🇰🇭',
                'full_name' => 'Kingdom of Cambodia',
                'top_level_domain' => '.kh',
            ),
            array(
                'id' => 72,
                'name' => 'Chad',
                'calling_code' => '235',
                'capital' => 'N\'Djamena',
                'code' => 'td',
                'code_alpha3' => 'tcd',
                'currency_code' => 'XAF',
                'currency_name' => 'CFA Franc BEAC',
                'emoji' => '🇹🇩',
                'full_name' => 'The Republic of Chad',
                'top_level_domain' => '.td',
            ),
            array(
                'id' => 73,
                'name' => 'Somalia',
                'calling_code' => '252',
                'capital' => 'Mogadishu',
                'code' => 'so',
                'code_alpha3' => 'som',
                'currency_code' => 'SOS',
                'currency_name' => 'Somali Shilling',
                'emoji' => '🇸🇴',
                'full_name' => 'The Somalia Democratic Republic',
                'top_level_domain' => '.so',
            ),
            array(
                'id' => 74,
                'name' => 'Guinea',
                'calling_code' => '224',
                'capital' => 'Conakry',
                'code' => 'gn',
                'code_alpha3' => 'gin',
                'currency_code' => 'GNF',
                'currency_name' => 'Guinea Franc',
                'emoji' => '🇬🇳',
                'full_name' => 'The Republic of Guinea',
                'top_level_domain' => '.gn',
            ),
            array(
                'id' => 75,
                'name' => 'South Sudan',
                'calling_code' => '211',
                'capital' => 'Juba',
                'code' => 'ss',
                'code_alpha3' => 'ssd',
                'currency_code' => 'SSP',
                'currency_name' => 'Sout Sudanese pound',
                'emoji' => '🇬🇳',
                'full_name' => 'The Republic of South Sudan',
                'top_level_domain' => '.ss',
            ),
            array(
                'id' => 76,
                'name' => 'Rwanda',
                'calling_code' => '250',
                'capital' => 'Kigali',
                'code' => 'rw',
                'code_alpha3' => 'rwa',
                'currency_code' => 'RWF',
                'currency_name' => 'Rwanda Franc',
                'emoji' => '🇷🇼',
                'full_name' => 'the Republic of Rwanda',
                'top_level_domain' => '.rw',
            ),
            array(
                'id' => 77,
                'name' => 'Benin',
                'calling_code' => '229',
                'capital' => 'Porto-Novo',
                'code' => 'bj',
                'code_alpha3' => 'ben',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇧🇯',
                'full_name' => 'the Republic of Benin ',
                'top_level_domain' => '.bj',
            ),
            array(
                'id' => 78,
                'name' => 'Tunisia',
                'calling_code' => '216',
                'capital' => 'Tunis',
                'code' => 'tn',
                'code_alpha3' => 'tun',
                'currency_code' => 'TND',
                'currency_name' => 'Tunisian Dinar',
                'emoji' => '🇹🇳',
                'full_name' => 'The Republic of Tunisia',
                'top_level_domain' => '.tn',
            ),
            array(
                'id' => 79,
                'name' => 'Burundi',
                'calling_code' => '257',
                'capital' => 'Bujumbura',
                'code' => 'bi',
                'code_alpha3' => 'bdi',
                'currency_code' => 'BIF',
                'currency_name' => 'Burundi Franc',
                'emoji' => '🇧🇮',
                'full_name' => 'The Republic of Burundi',
                'top_level_domain' => '.bi',
            ),
            array(
                'id' => 80,
                'name' => 'Belgium',
                'calling_code' => '32',
                'capital' => 'Brussels',
                'code' => 'be',
                'code_alpha3' => 'bel',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇧🇪',
                'full_name' => 'The Kingdom Of Belgium',
                'top_level_domain' => '.be',
            ),
            array(
                'id' => 81,
                'name' => 'Cuba',
                'calling_code' => '53',
                'capital' => 'Havana',
                'code' => 'cu',
                'code_alpha3' => 'cub',
                'currency_code' => 'CUC',
                'currency_name' => 'Cuban convertible peso',
                'emoji' => '🇨🇺',
                'full_name' => 'The Republic of Cuba',
                'top_level_domain' => '.cu',
            ),
            array(
                'id' => 82,
                'name' => 'Bolivia',
                'calling_code' => '591',
                'capital' => 'Sucre',
                'code' => 'bo',
                'code_alpha3' => 'bol',
                'currency_code' => 'BOB',
                'currency_name' => 'Boliviano',
                'emoji' => '🇧🇴',
                'full_name' => 'The Republic of Bolivia',
                'top_level_domain' => '.bo',
            ),
            array(
                'id' => 83,
                'name' => 'Haiti',
                'calling_code' => '509',
                'capital' => 'Port-au-Prince',
                'code' => 'ht',
                'code_alpha3' => 'hti',
                'currency_code' => 'HTG',
                'currency_name' => 'Haitian gourde',
                'emoji' => '🇭🇹',
                'full_name' => 'The Republic of Haiti',
                'top_level_domain' => '.ht',
            ),
            array(
                'id' => 84,
                'name' => 'Greece',
                'calling_code' => '30',
                'capital' => 'Athens',
                'code' => 'gr',
                'code_alpha3' => 'grc',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇬🇷',
                'full_name' => 'The Hellenic Republic',
                'top_level_domain' => '.gr',
            ),
            array(
                'id' => 85,
                'name' => 'Dominican Republic',
                'calling_code' => '1809',
                'capital' => 'Santo Domingo',
                'code' => 'do',
                'code_alpha3' => 'dom',
                'currency_code' => 'DOP',
                'currency_name' => 'Dominican Peso',
                'emoji' => '🇩🇴',
                'full_name' => 'The Dominican Republic',
                'top_level_domain' => '.do',
            ),
            array(
                'id' => 86,
                'name' => 'Czech',
                'calling_code' => '420',
                'capital' => 'Prague',
                'code' => 'cz',
                'code_alpha3' => 'cze',
                'currency_code' => 'CZK',
                'currency_name' => 'Czech Koruna',
                'emoji' => '🇨🇿',
                'full_name' => 'The Czech Republic',
                'top_level_domain' => '.cz',
            ),
            array(
                'id' => 87,
                'name' => 'Portugal',
                'calling_code' => '351',
                'capital' => 'Lisbon',
                'code' => 'pt',
                'code_alpha3' => 'prt',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇵🇹',
                'full_name' => 'Portugal,the Portuguese Republic',
                'top_level_domain' => '.pt',
            ),
            array(
                'id' => 88,
                'name' => 'Jordan',
                'calling_code' => '962',
                'capital' => 'Amman',
                'code' => 'jo',
                'code_alpha3' => 'jor',
                'currency_code' => 'JOD',
                'currency_name' => 'Jordanian Dinar',
                'emoji' => '🇯🇴',
                'full_name' => 'The Hashemite Kingdom of Jordan',
                'top_level_domain' => '.jo',
            ),
            array(
                'id' => 89,
                'name' => 'Sweden',
                'calling_code' => '46',
                'capital' => 'Stockholm',
                'code' => 'se',
                'code_alpha3' => 'swe',
                'currency_code' => 'SEK',
                'currency_name' => 'Swedish Krona',
                'emoji' => '🇸🇪',
                'full_name' => 'The Kingdom of Sweden',
                'top_level_domain' => '.se',
            ),
            array(
                'id' => 90,
                'name' => 'Azerbaijan',
                'calling_code' => '994',
                'capital' => 'Baku',
                'code' => 'az',
                'code_alpha3' => 'aze',
                'currency_code' => 'AZN',
                'currency_name' => 'Azerbaijanian Manat',
                'emoji' => '🇦🇿',
                'full_name' => 'The Republic of Azerbaijan',
                'top_level_domain' => '.az',
            ),
            array(
                'id' => 91,
                'name' => 'United Arab Emirates',
                'calling_code' => '971',
                'capital' => 'Abu Dhabi',
                'code' => 'ae',
                'code_alpha3' => 'are',
                'currency_code' => 'AED',
                'currency_name' => 'UAE Dirham',
                'emoji' => '🇦🇪',
                'full_name' => 'The United Arab Emirates',
                'top_level_domain' => '.ae',
            ),
            array(
                'id' => 92,
                'name' => 'Hungary',
                'calling_code' => '36',
                'capital' => 'Budapest',
                'code' => 'hu',
                'code_alpha3' => 'hun',
                'currency_code' => 'HUF',
                'currency_name' => 'Forint',
                'emoji' => '🇭🇺',
                'full_name' => 'Hungary',
                'top_level_domain' => '.hu',
            ),
            array(
                'id' => 93,
                'name' => 'Honduras',
                'calling_code' => '504',
                'capital' => 'Tegucigalpa',
                'code' => 'hn',
                'code_alpha3' => 'hnd',
                'currency_code' => 'HNL',
                'currency_name' => 'Lempira',
                'emoji' => '🇭🇳',
                'full_name' => 'Republic of Honduras',
                'top_level_domain' => '.hn',
            ),
            array(
                'id' => 94,
                'name' => 'Belarus',
                'calling_code' => '375',
                'capital' => 'Minsk',
                'code' => 'by',
                'code_alpha3' => 'blr',
                'currency_code' => 'BYR',
                'currency_name' => 'Belarussian Ruble',
                'emoji' => '🇧🇾',
                'full_name' => 'The Republic of Belarus',
                'top_level_domain' => '.by',
            ),
            array(
                'id' => 95,
                'name' => 'Tajikistan',
                'calling_code' => '992',
                'capital' => 'Dushanbe',
                'code' => 'tj',
                'code_alpha3' => 'tjk',
                'currency_code' => 'TJS',
                'currency_name' => 'Somoni',
                'emoji' => '🇹🇯',
                'full_name' => 'The Republic of Tajikistan',
                'top_level_domain' => '.tj',
            ),
            array(
                'id' => 96,
                'name' => 'Austria',
                'calling_code' => '43',
                'capital' => 'Vienna',
                'code' => 'at',
                'code_alpha3' => 'aut',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇦🇹',
                'full_name' => 'The Republic Of Austria',
                'top_level_domain' => '.at',
            ),
            array(
                'id' => 97,
                'name' => 'Serbia',
                'calling_code' => '381',
                'capital' => 'Belgrade',
                'code' => 'rs',
                'code_alpha3' => 'srb',
                'currency_code' => 'RSD',
                'currency_name' => 'Serbian Dinar',
                'emoji' => '🇷🇸',
                'full_name' => 'Republic of Serbia',
                'top_level_domain' => '.rs',
            ),
            array(
                'id' => 98,
                'name' => 'Switzerland',
                'calling_code' => '41',
                'capital' => 'Bern',
                'code' => 'ch',
                'code_alpha3' => 'che',
                'currency_code' => 'CHE',
                'currency_name' => 'WIR Euro (complementary currency)',
                'emoji' => '🇨🇭',
                'full_name' => 'Swiss Confederation',
                'top_level_domain' => '.ch',
            ),
            array(
                'id' => 99,
                'name' => 'Papua New Guinea',
                'calling_code' => '675',
                'capital' => 'Port Moresby',
                'code' => 'pg',
                'code_alpha3' => 'png',
                'currency_code' => 'PGK',
                'currency_name' => 'Kina',
                'emoji' => '🇵🇬',
                'full_name' => 'The Independent State of Papua New Guinea',
                'top_level_domain' => '.pg',
            ),
            array(
                'id' => 100,
                'name' => 'Israel',
                'calling_code' => '972',
                'capital' => 'Jerusalem',
                'code' => 'il',
                'code_alpha3' => 'isr',
                'currency_code' => 'ILS',
                'currency_name' => 'New Israeli Sheqel',
                'emoji' => '🇮🇱',
                'full_name' => 'The State of Israel',
                'top_level_domain' => '.il',
            ),
            array(
                'id' => 101,
                'name' => 'Togo',
                'calling_code' => '228',
                'capital' => 'Lomé',
                'code' => 'tg',
                'code_alpha3' => 'tgo',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇹🇬',
                'full_name' => 'The Republic of Togo',
                'top_level_domain' => '.tg',
            ),
            array(
                'id' => 102,
                'name' => 'Sierra Leone',
                'calling_code' => '232',
                'capital' => 'Freetown',
                'code' => 'sl',
                'code_alpha3' => 'sle',
                'currency_code' => 'SLL',
                'currency_name' => 'Leone',
                'emoji' => '🇸🇱',
                'full_name' => 'The Republic of Sierra Leone',
                'top_level_domain' => '.sl',
            ),
            array(
                'id' => 103,
                'name' => 'Laos',
                'calling_code' => '856',
                'capital' => 'Vientiane',
                'code' => 'la',
                'code_alpha3' => 'lao',
                'currency_code' => 'LAK',
                'currency_name' => 'Kip',
                'emoji' => '🇱🇦',
                'full_name' => 'Lao People\'s Democratic Republic',
                'top_level_domain' => '.la',
            ),
            array(
                'id' => 104,
                'name' => 'Bulgaria',
                'calling_code' => '359',
                'capital' => 'Sofia',
                'code' => 'bg',
                'code_alpha3' => 'bgr',
                'currency_code' => 'BGN',
                'currency_name' => 'Bulgarian Lev',
                'emoji' => '🇧🇬',
                'full_name' => 'Republic of Bulgaria',
                'top_level_domain' => '.bg',
            ),
            array(

                'id' => 105,
                'name' => 'Paraguay',
                'calling_code' => '595',
                'capital' => 'Asunción',
                'code' => 'py',
                'code_alpha3' => 'pry',
                'currency_code' => 'PYG',
                'currency_name' => 'Guarani',
                'emoji' => '🇵🇾',
                'full_name' => 'The Republic of Paraguay',
                'top_level_domain' => '.py',
            ),
            array(

                'id' => 106,
                'name' => 'Libya',
                'calling_code' => '218',
                'capital' => 'Tripoli',
                'code' => 'ly',
                'code_alpha3' => 'lby',
                'currency_code' => 'LYD',
                'currency_name' => 'Libyan Dinar',
                'emoji' => '🇱🇾',
                'full_name' => 'State of Libya',
                'top_level_domain' => '.ly',
            ),
            array(

                'id' => 107,
                'name' => 'El Salvador',
                'calling_code' => '503',
                'capital' => 'San Salvador',
                'code' => 'sv',
                'code_alpha3' => 'slv',
                'currency_code' => 'SVC',
                'currency_name' => 'Salvadoran colón',
                'emoji' => '🇸🇻',
                'full_name' => 'The Republic of El Salvador',
                'top_level_domain' => '.sv',
            ),
            array(

                'id' => 108,
                'name' => 'Nicaragua',
                'calling_code' => '505',
                'capital' => 'Managua',
                'code' => 'ni',
                'code_alpha3' => 'nic',
                'currency_code' => 'NIO',
                'currency_name' => 'Cordoba Oro',
                'emoji' => '🇳🇮',
                'full_name' => 'The Republic of Nicaragua',
                'top_level_domain' => '.ni',
            ),
            array(

                'id' => 109,
                'name' => 'Kyrgyzstan',
                'calling_code' => '996',
                'capital' => 'Bishkek',
                'code' => 'kg',
                'code_alpha3' => 'kgz',
                'currency_code' => 'KGS',
                'currency_name' => 'Som',
                'emoji' => '🇰🇬',
                'full_name' => 'The Kyrgyz Republic',
                'top_level_domain' => '.kg',
            ),
            array(
                'id' => 110,
                'name' => 'Lebanon',
                'calling_code' => '961',
                'capital' => 'Beirut',
                'code' => 'lb',
                'code_alpha3' => 'lbn',
                'currency_code' => 'LBP',
                'currency_name' => 'Lebanese Pound',
                'emoji' => '🇱🇧',
                'full_name' => 'The Republic of Lebanon',
                'top_level_domain' => '.lb',
            ),
            array(

                'id' => 111,
                'name' => 'Turkmenistan',
                'calling_code' => '993',
                'capital' => 'Ashgabat',
                'code' => 'tm',
                'code_alpha3' => 'tkm',
                'currency_code' => 'TMT',
                'currency_name' => 'Turkmenistan New Manat',
                'emoji' => '🇹🇲',
                'full_name' => 'Turkmenistan',
                'top_level_domain' => '.tm',
            ),
            array(

                'id' => 112,
                'name' => 'Singapore',
                'calling_code' => '65',
                'capital' => 'Singapore',
                'code' => 'sg',
                'code_alpha3' => 'sgp',
                'currency_code' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'emoji' => '🇸🇬',
                'full_name' => 'Republic of Singapore',
                'top_level_domain' => '.sg',
            ),
            array(

                'id' => 113,
                'name' => 'Denmark',
                'calling_code' => '45',
                'capital' => 'Copenhagen',
                'code' => 'dk',
                'code_alpha3' => 'dnk',
                'currency_code' => 'DKK',
                'currency_name' => 'Danish Krone',
                'emoji' => '🇩🇰',
                'full_name' => 'The Kingdom of Denmark',
                'top_level_domain' => '.dk',
            ),
            array(

                'id' => 114,
                'name' => 'Finland',
                'calling_code' => '358',
                'capital' => 'Helsinki',
                'code' => 'fi',
                'code_alpha3' => 'fin',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇫🇮',
                'full_name' => 'The Republic of Finland',
                'top_level_domain' => '.fi',
            ),
            array(

                'id' => 115,
                'name' => 'DR Congo',
                'calling_code' => '243',
                'capital' => 'Kinshasa',
                'code' => 'cd',
                'code_alpha3' => 'cod',
                'currency_code' => 'CDF',
                'currency_name' => 'Congolese franc',
                'emoji' => '🇨🇩',
                'full_name' => 'Democratic Republic of the Congo',
                'top_level_domain' => '.cd',
            ),
            array(
                'id' => 116,
                'name' => 'Slovak',
                'calling_code' => '421',
                'capital' => 'Bratislava',
                'code' => 'sk',
                'code_alpha3' => 'svk',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇸🇰',
                'full_name' => 'The Slovak Republic',
                'top_level_domain' => '.sk',
            ),
            array(

                'id' => 117,
                'name' => 'Norway',
                'calling_code' => '47',
                'capital' => 'Oslo',
                'code' => 'no',
                'code_alpha3' => 'nor',
                'currency_code' => 'NOK',
                'currency_name' => 'Norwegian Krone',
                'emoji' => '🇳🇴',
                'full_name' => 'The Kingdom of Norway',
                'top_level_domain' => '.no',
            ),
            array(

                'id' => 118,
                'name' => 'Eritrea',
                'calling_code' => '291',
                'capital' => 'Asmara',
                'code' => 'er',
                'code_alpha3' => 'eri',
                'currency_code' => 'ERN',
                'currency_name' => 'Nakfa',
                'emoji' => '🇪🇷',
                'full_name' => 'the Commonwealth of Eritrea',
                'top_level_domain' => '.er',
            ),
            array(
                'id' => 119,
                'name' => 'Palestine',
                'calling_code' => '970',
                'capital' => 'Ramallah',
                'code' => 'ps',
                'code_alpha3' => 'pal',
                'currency_code' => 'ILS',
                'currency_name' => 'Israeli new shekel',
                'emoji' => '🇵🇸',
                'full_name' => 'State of Palestine',
                'top_level_domain' => '.ps',
            ),
            array(
                'id' => 120,
                'name' => 'Oman',
                'calling_code' => '968',
                'capital' => 'Muscat',
                'code' => 'om',
                'code_alpha3' => 'omn',
                'currency_code' => 'OMR',
                'currency_name' => 'Rial Omani',
                'emoji' => '🇴🇲',
                'full_name' => 'Sultanate of Oman',
                'top_level_domain' => '.om',
            ),
            array(
                'id' => 121,
                'name' => 'Costa Rica',
                'calling_code' => '506',
                'capital' => 'San José',
                'code' => 'cr',
                'code_alpha3' => 'cri',
                'currency_code' => 'CRC',
                'currency_name' => 'Costa Rican Colon',
                'emoji' => '🇨🇷',
                'full_name' => 'Republic of Costa Rica',
                'top_level_domain' => '.cr',
            ),
            array(
                'id' => 122,
                'name' => 'Liberia',
                'calling_code' => '231',
                'capital' => 'Monrovia',
                'code' => 'lr',
                'code_alpha3' => 'lbr',
                'currency_code' => 'LRD',
                'currency_name' => 'Liberian Dollar',
                'emoji' => '🇱🇷',
                'full_name' => 'The Republic of Liberia',
                'top_level_domain' => '.lr',
            ),
            array(
                'id' => 123,
                'name' => 'Ireland',
                'calling_code' => '353',
                'capital' => 'Dublin',
                'code' => 'ie',
                'code_alpha3' => 'irl',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇮🇪',
                'full_name' => 'The Republic of Ireland',
                'top_level_domain' => '.ie',
            ),
            array(
                'id' => 124,
                'name' => 'Central African',
                'calling_code' => '236',
                'capital' => 'Bangui',
                'code' => 'cf',
                'code_alpha3' => 'caf',
                'currency_code' => 'XAF',
                'currency_name' => 'CFA Franc BEAC',
                'emoji' => '🇨🇫',
                'full_name' => 'The Central African Republic',
                'top_level_domain' => '.cf',
            ),
            array(

                'id' => 125,
                'name' => 'Cook Is',
                'calling_code' => '682',
                'capital' => 'Avarua',
                'code' => 'ck',
                'code_alpha3' => 'cok',
                'currency_code' => 'NZD',
                'currency_name' => 'New Zealand Dollar',
                'emoji' => '🇨🇰',
                'full_name' => 'The Cook Islands',
                'top_level_domain' => '.ck',
            ),
            array(
                'id' => 126,
                'name' => 'Mauritania',
                'calling_code' => '222',
                'capital' => 'Nouakchott',
                'code' => 'mr',
                'code_alpha3' => 'mrt',
                'currency_code' => 'MRO',
                'currency_name' => 'Ouguiya',
                'emoji' => '🇲🇷',
                'full_name' => 'The Islamic Republic of Mauritania',
                'top_level_domain' => '.mr',
            ),
            array(

                'id' => 127,
                'name' => 'Kuwait',
                'calling_code' => '965',
                'capital' => 'Kuwait CityCms',
                'code' => 'kw',
                'code_alpha3' => 'kwt',
                'currency_code' => 'KWD',
                'currency_name' => 'Kuwaiti Dinar',
                'emoji' => '🇰🇼',
                'full_name' => 'The State of Kuwait',
                'top_level_domain' => '.kw',
            ),
            array(

                'id' => 128,
                'name' => 'Panama',
                'calling_code' => '507',
                'capital' => 'Panama CityCms',
                'code' => 'pa',
                'code_alpha3' => 'pan',
                'currency_code' => 'PAB',
                'currency_name' => 'Panamanian balboa',
                'emoji' => '🇵🇦',
                'full_name' => 'The Republic of Panama',
                'top_level_domain' => '.pa',
            ),
            array(
                'id' => 129,
                'name' => 'Croatia',
                'calling_code' => '385',
                'capital' => 'Zagreb',
                'code' => 'hr',
                'code_alpha3' => 'hrv',
                'currency_code' => 'HRK',
                'currency_name' => 'Croatian Kuna',
                'emoji' => '🇭🇷',
                'full_name' => 'The Republic of Croatia',
                'top_level_domain' => '.hr',
            ),
            array(

                'id' => 130,
                'name' => 'Moldova',
                'calling_code' => '373',
                'capital' => 'Chisinau',
                'code' => 'md',
                'code_alpha3' => 'mda',
                'currency_code' => 'MDL',
                'currency_name' => 'Moldovan leu',
                'emoji' => '🇲🇩',
                'full_name' => 'Republic of Moldova',
                'top_level_domain' => '.md',
            ),
            array(
                'id' => 131,
                'name' => 'Georgia',
                'calling_code' => '995',
                'capital' => 'Tbilisi',
                'code' => 'ge',
                'code_alpha3' => 'geo',
                'currency_code' => 'GEL',
                'currency_name' => 'Lari',
                'emoji' => '🇬🇪',
                'full_name' => 'Georgia',
                'top_level_domain' => '.ge',
            ),
            array(
                'id' => 132,
                'name' => 'Bosnia Hercegovina',
                'calling_code' => '387',
                'capital' => 'Sarajevo',
                'code' => 'ba',
                'code_alpha3' => 'bih',
                'currency_code' => 'BAM',
                'currency_name' => 'Convertible Mark',
                'emoji' => '🇧🇦',
                'full_name' => 'Bosnia and Herzegovina',
                'top_level_domain' => '.ba',
            ),
            array (
                'id' => 133,
                'name' => 'Uruguay',
                'calling_code' => '598',
                'capital' => 'Montevideo',
                'code' => 'uy',
                'code_alpha3' => 'ury',
                'currency_code' => 'UYU',
                'currency_name' => 'Peso Uruguayo',
                'emoji' => '🇺🇾',
                'full_name' => 'The Oriental Republic of Uruguay',
                'top_level_domain' => '.uy',
            ),
            array (
                'id' => 134,
                'name' => 'Mongolia',
                'calling_code' => '976',
                'capital' => 'Ulan Bator',
                'code' => 'mn',
                'code_alpha3' => 'mng',
                'currency_code' => 'MNT',
                'currency_name' => 'Tugrik',
                'emoji' => '🇲🇳',
                'full_name' => 'Mongolia',
                'top_level_domain' => '.mn',
            ),
            array (
                'id' => 135,
                'name' => 'Albania',
                'calling_code' => '355',
                'capital' => 'Tirana',
                'code' => 'al',
                'code_alpha3' => 'alb',
                'currency_code' => 'ALL',
                'currency_name' => 'Lek',
                'emoji' => '🇦🇱',
                'full_name' => 'The Republic of Albania',
                'top_level_domain' => '.al',
            ),
            array (

                'id' => 136,
                'name' => 'Armenia',
                'calling_code' => '374',
                'capital' => 'Yerevan',
                'code' => 'am',
                'code_alpha3' => 'arm',
                'currency_code' => 'AMD',
                'currency_name' => 'Armenian Dram',
                'emoji' => '🇦🇲',
                'full_name' => 'The Republic of Armenia',
                'top_level_domain' => '.am',
            ),
            array (
                'id' => 137,
                'name' => 'Jamaica',
                'calling_code' => '1876',
                'capital' => 'Kingston',
                'code' => 'jm',
                'code_alpha3' => 'jam',
                'currency_code' => 'JMD',
                'currency_name' => 'Jamaican Dollar',
                'emoji' => '🇯🇲',
                'full_name' => 'Jamaica',
                'top_level_domain' => '.jm',
            ),
            array (

                'id' => 138,
                'name' => 'Lithuania',
                'calling_code' => '370',
                'capital' => 'Vilnius',
                'code' => 'lt',
                'code_alpha3' => 'ltu',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇱🇹',
                'full_name' => 'The Republic of Lithuania',
                'top_level_domain' => '.lt',
            ),
            array (
                'id' => 139,
                'name' => 'Qatar',
                'calling_code' => '974',
                'capital' => 'Doha',
                'code' => 'qa',
                'code_alpha3' => 'qat',
                'currency_code' => 'QAR',
                'currency_name' => 'Qatari Rial',
                'emoji' => '🇶🇦',
                'full_name' => 'The State of Qatar',
                'top_level_domain' => '.qa',
            ),
            array (
                'id' => 140,
                'name' => 'Namibia',
                'calling_code' => '264',
                'capital' => 'Windhoek',
                'code' => 'na',
                'code_alpha3' => 'nam',
                'currency_code' => 'NAD',
                'currency_name' => 'Namibian dollar',
                'emoji' => '🇳🇦',
                'full_name' => 'The Republic of Namibia',
                'top_level_domain' => '.na',
            ),
            array (

                'id' => 141,
                'name' => 'Botswana',
                'calling_code' => '267',
                'capital' => 'Gaborone',
                'code' => 'bw',
                'code_alpha3' => 'bwa',
                'currency_code' => 'BWP',
                'currency_name' => 'Pula',
                'emoji' => '🇧🇼',
                'full_name' => 'The Republic of Botswana',
                'top_level_domain' => '.bw',
            ),
            array (

                'id' => 142,
                'name' => 'Lesotho',
                'calling_code' => '266',
                'capital' => 'Maseru',
                'code' => 'ls',
                'code_alpha3' => 'lso',
                'currency_code' => 'LSL',
                'currency_name' => 'Lesotho loti',
                'emoji' => '🇱🇸',
                'full_name' => 'The Kingdom of Lesotho',
                'top_level_domain' => '.ls',
            ),
            array (

                'id' => 143,
                'name' => 'Gambia',
                'calling_code' => '590',
                'capital' => 'Basse-Terre',
                'code' => 'gp',
                'code_alpha3' => 'gmb',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇬🇵',
                'full_name' => 'Islamic Republic of Gambia',
                'top_level_domain' => '.gp',
            ),
            array (

                'id' => 144,
                'name' => 'Gabon',
                'calling_code' => '241',
                'capital' => 'Libreville',
                'code' => 'ga',
                'code_alpha3' => 'gab',
                'currency_code' => 'XAF',
                'currency_name' => 'CFA Franc BEAC',
                'emoji' => '🇬🇦',
                'full_name' => 'The Gabonese Republic',
                'top_level_domain' => '.ga',
            ),
            array (
                'id' => 145,
                'name' => 'North Macedonia',
                'calling_code' => '389',
                'capital' => 'Skopje',
                'code' => 'mk',
                'code_alpha3' => 'mkd',
                'currency_code' => 'MKD',
                'currency_name' => 'Macedonian denar',
                'emoji' => '🇲🇰',
                'full_name' => 'Republic of North Macedonia',
                'top_level_domain' => '.mk',
            ),
            array (
                'id' => 146,
                'name' => 'Slovenia',
                'calling_code' => '386',
                'capital' => 'Ljubljana',
                'code' => 'si',
                'code_alpha3' => 'svn',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇸🇮',
                'full_name' => 'The Republic of Slovenia',
                'top_level_domain' => '.si',
            ),
            array (

                'id' => 147,
                'name' => 'Guinea Bissau',
                'calling_code' => '245',
                'capital' => 'Bissau',
                'code' => 'gw',
                'code_alpha3' => 'gnb',
                'currency_code' => 'XOF',
                'currency_name' => 'CFA Franc BCEAO',
                'emoji' => '🇬🇼',
                'full_name' => 'The Republic of Guinea-Bissau',
                'top_level_domain' => '.gw',
            ),
            array (
                'id' => 148,
                'name' => 'Latvia',
                'calling_code' => '371',
                'capital' => 'Riga',
                'code' => 'lv',
                'code_alpha3' => 'lva',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇱🇻',
                'full_name' => 'Republic of Latvia',
                'top_level_domain' => '.lv',
            ),
            array (
                'id' => 149,
                'name' => 'Bahrian',
                'calling_code' => '973',
                'capital' => 'Manama',
                'code' => 'bh',
                'code_alpha3' => 'bhr',
                'currency_code' => 'BHD',
                'currency_name' => 'Bahraini Dinar',
                'emoji' => '🇧🇭',
                'full_name' => 'The Kingdom of Bahrain',
                'top_level_domain' => '.bh',
            ),
            array (
                'id' => 150,
                'name' => 'Swaziland',
                'calling_code' => '268',
                'capital' => 'Lobamba',
                'code' => 'sz',
                'code_alpha3' => 'swz',
                'currency_code' => 'SZL',
                'currency_name' => 'Lilangeni',
                'emoji' => '🇸🇿',
                'full_name' => 'The Kingdom of Swaziland',
                'top_level_domain' => '.sz',
            ),
            array (
                'id' => 151,
                'name' => 'Trinidad and Tobago',
                'calling_code' => '1868',
                'capital' => 'Port of Spain',
                'code' => 'tt',
                'code_alpha3' => 'tto',
                'currency_code' => 'TTD',
                'currency_name' => 'Trinidad and Tobago Dollar',
                'emoji' => '🇹🇹',
                'full_name' => 'Republic of Trinidad and Tobago',
                'top_level_domain' => '.tt',
            ),
            array (
                'id' => 152,
                'name' => 'Equatorial Guinea',
                'calling_code' => '240',
                'capital' => 'Malabo',
                'code' => 'gq',
                'code_alpha3' => 'gnq',
                'currency_code' => 'XAF',
                'currency_name' => 'CFA Franc BEAC',
                'emoji' => '🇬🇶',
                'full_name' => 'Republic of Equatorial Guinea',
                'top_level_domain' => '.gq',
            ),
            array (

                'id' => 153,
                'name' => 'Timor-Leste',
                'calling_code' => '670',
                'capital' => 'Dili',
                'code' => 'tl',
                'code_alpha3' => 'tmp',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇹🇱',
                'full_name' => 'Democratic Republic of Timor-Leste',
                'top_level_domain' => '.tl',
            ),
            array (
                'id' => 154,
                'name' => 'Estonia',
                'calling_code' => '372',
                'capital' => 'Tallinn',
                'code' => 'ee',
                'code_alpha3' => 'est',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇪🇪',
                'full_name' => 'Republic of Estonia',
                'top_level_domain' => '.ee',
            ),
            array (

                'id' => 155,
                'name' => 'Mauritius',
                'calling_code' => '230',
                'capital' => 'Port Louis',
                'code' => 'mu',
                'code_alpha3' => 'mus',
                'currency_code' => 'MUR',
                'currency_name' => 'Mauritius Rupee',
                'emoji' => '🇲🇺',
                'full_name' => 'the Republic of Mauritius',
                'top_level_domain' => '.mu',
            ),
            array (

                'id' => 156,
                'name' => 'Cyprus',
                'calling_code' => '357',
                'capital' => 'Nicosia',
                'code' => 'cy',
                'code_alpha3' => 'cyp',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇨🇾',
                'full_name' => 'the Republic of Cyprus',
                'top_level_domain' => '.cy',
            ),
            array (
                'id' => 157,
                'name' => 'Djibouti',
                'calling_code' => '253',
                'capital' => 'Djibouti',
                'code' => 'dj',
                'code_alpha3' => 'dji',
                'currency_code' => 'DJF',
                'currency_name' => 'Djibouti Franc',
                'emoji' => '🇩🇯',
                'full_name' => 'The Republic of Djibouti',
                'top_level_domain' => '.dj',
            ),
            array (

                'id' => 158,
                'name' => 'Fiji',
                'calling_code' => '679',
                'capital' => 'Suva',
                'code' => 'fj',
                'code_alpha3' => 'fji',
                'currency_code' => 'FJD',
                'currency_name' => 'Fiji Dollar',
                'emoji' => '🇫🇯',
                'full_name' => 'The Republic of Fiji',
                'top_level_domain' => '.fj',
            ),
            array (

                'id' => 159,
                'name' => 'Comoros',
                'calling_code' => '269',
                'capital' => 'Moroni',
                'code' => 'km',
                'code_alpha3' => 'com',
                'currency_code' => 'KMF',
                'currency_name' => 'Comoro Franc',
                'emoji' => '🇰🇲',
                'full_name' => 'Union of Comoros',
                'top_level_domain' => '.km',
            ),
            array (

                'id' => 160,
                'name' => 'Bhutan',
                'calling_code' => '975',
                'capital' => 'Thimphu',
                'code' => 'bt',
                'code_alpha3' => 'btn',
                'currency_code' => 'BTN',
                'currency_name' => 'Bhutanese ngultrum',
                'emoji' => '🇧🇹',
                'full_name' => 'Kingdom of Bhutan',
                'top_level_domain' => '.bt',
            ),
            array (

                'id' => 161,
                'name' => 'Guyana',
                'calling_code' => '592',
                'capital' => 'Georgetown',
                'code' => 'gy',
                'code_alpha3' => 'guy',
                'currency_code' => 'GYD',
                'currency_name' => 'Guyana Dollar',
                'emoji' => '🇬🇾',
                'full_name' => 'The Republic of Guyana',
                'top_level_domain' => '.gy',
            ),
            array (
                'id' => 162,
                'name' => 'Solomon Is',
                'calling_code' => '677',
                'capital' => 'Honiara',
                'code' => 'sb',
                'code_alpha3' => 'slb',
                'currency_code' => 'SBD',
                'currency_name' => 'Solomon Islands Dollar',
                'emoji' => '🇸🇧',
                'full_name' => 'Solomon Islands',
                'top_level_domain' => '.sb',
            ),
            array (
                'id' => 163,
                'name' => 'Montenegro',
                'calling_code' => '382',
                'capital' => 'Podgorica',
                'code' => 'me',
                'code_alpha3' => 'mne',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇲🇪',
                'full_name' => 'Montenegro',
                'top_level_domain' => '.me',
            ),
            array (

                'id' => 164,
                'name' => 'Luxembourg',
                'calling_code' => '352',
                'capital' => 'Luxembourg',
                'code' => 'lu',
                'code_alpha3' => 'lux',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇱🇺',
                'full_name' => 'The Grand Duchy of Luxembourg',
                'top_level_domain' => '.lu',
            ),
            array (

                'id' => 165,
                'name' => 'Suriname',
                'calling_code' => '597',
                'capital' => 'Paramaribo',
                'code' => 'sr',
                'code_alpha3' => 'sur',
                'currency_code' => 'SRD',
                'currency_name' => 'Surinam Dollar',
                'emoji' => '🇸🇷',
                'full_name' => 'The Republic of Suriname',
                'top_level_domain' => '.sr',
            ),
            array (
                'id' => 166,
                'name' => 'Cape Verde',
                'calling_code' => '238',
                'capital' => 'Praia',
                'code' => 'cv',
                'code_alpha3' => 'cpv',
                'currency_code' => 'CVE',
                'currency_name' => 'Cabo Verde Escudo',
                'emoji' => '🇨🇻',
                'full_name' => 'The Republic of Cape Verde',
                'top_level_domain' => '.cv',
            ),
            array (
                'id' => 167,
                'name' => 'Micronesia',
                'calling_code' => '691',
                'capital' => 'Palikir',
                'code' => 'fm',
                'code_alpha3' => 'fsm',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇫🇲',
                'full_name' => 'Federated States of Micronesia',
                'top_level_domain' => '.fm',
            ),
            array (
                'id' => 168,
                'name' => 'Maldives',
                'calling_code' => '960',
                'capital' => 'Malé',
                'code' => 'mv',
                'code_alpha3' => 'mdv',
                'currency_code' => 'MVR',
                'currency_name' => 'Rufiyaa',
                'emoji' => '🇲🇻',
                'full_name' => 'The Republic of Maldives',
                'top_level_domain' => '.mv',
            ),
            array (
                'id' => 169,
                'name' => 'Brunei',
                'calling_code' => '673',
                'capital' => 'Bandar Seri Begawan',
                'code' => 'bn',
                'code_alpha3' => 'brn',
                'currency_code' => 'BND',
                'currency_name' => 'Brunei Dollar',
                'emoji' => '🇧🇳',
                'full_name' => 'Brunei Darussalam',
                'top_level_domain' => '.bn',
            ),
            array (

                'id' => 170,
                'name' => 'Malta',
                'calling_code' => '356',
                'capital' => 'Valletta',
                'code' => 'mt',
                'code_alpha3' => 'mlt',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇲🇹',
                'full_name' => 'Republic of Malta',
                'top_level_domain' => '.mt',
            ),
            array (
                'id' => 171,
                'name' => 'Bahamas',
                'calling_code' => '1242',
                'capital' => 'Nassau',
                'code' => 'bs',
                'code_alpha3' => 'bhs',
                'currency_code' => 'BSD',
                'currency_name' => 'Bahamian Dollar',
                'emoji' => '🇧🇸',
                'full_name' => 'The Commonwealth of The Bahamas',
                'top_level_domain' => '.bs',
            ),
            array (

                'id' => 172,
                'name' => 'Belize',
                'calling_code' => '501',
                'capital' => 'Belmopan',
                'code' => 'bz',
                'code_alpha3' => 'blz',
                'currency_code' => 'BZD',
                'currency_name' => 'Belize Dollar',
                'emoji' => '🇧🇿',
                'full_name' => 'Belize',
                'top_level_domain' => '.bz',
            ),
            array (

                'id' => 173,
                'name' => 'Iceland',
                'calling_code' => '354',
                'capital' => 'Reykjavik',
                'code' => 'is',
                'code_alpha3' => 'isl',
                'currency_code' => 'ISK',
                'currency_name' => 'Iceland Krona',
                'emoji' => '🇮🇸',
                'full_name' => 'The Republic of Iceland',
                'top_level_domain' => '.is',
            ),
            array (
                'id' => 174,
                'name' => 'Vanuatu',
                'calling_code' => '678',
                'capital' => 'Port Vila',
                'code' => 'vu',
                'code_alpha3' => 'vut',
                'currency_code' => 'VUV',
                'currency_name' => 'Vatu',
                'emoji' => '🇻🇺',
                'full_name' => 'Republic of Vanuatu',
                'top_level_domain' => '.vu',
            ),
            array (

                'id' => 175,
                'name' => 'Barbados',
                'calling_code' => '1246',
                'capital' => 'Bridgetown',
                'code' => 'bb',
                'code_alpha3' => 'brb',
                'currency_code' => 'BBD',
                'currency_name' => 'Barbados Dollar',
                'emoji' => '🇧🇧',
                'full_name' => 'Barbados',
                'top_level_domain' => '.bb',
            ),
            array (

                'id' => 176,
                'name' => 'Sao Tome and Principe',
                'calling_code' => '239',
                'capital' => 'São Tomé',
                'code' => 'st',
                'code_alpha3' => 'stp',
                'currency_code' => 'STD',
                'currency_name' => 'Dobra',
                'emoji' => '🇸🇹',
                'full_name' => 'the Democratic Republic Sao Tome and Principe',
                'top_level_domain' => '.st',
            ),
            array (
                'id' => 177,
                'name' => 'Samoa',
                'calling_code' => '685',
                'capital' => 'Apia',
                'code' => 'ws',
                'code_alpha3' => 'wsm',
                'currency_code' => 'WST',
                'currency_name' => 'Tala',
                'emoji' => '🇼🇸',
                'full_name' => 'The Independent State of Samoa',
                'top_level_domain' => '.ws',
            ),
            array (

                'id' => 178,
                'name' => 'Saint Lucia',
                'calling_code' => '1758',
                'capital' => 'Castries',
                'code' => 'lc',
                'code_alpha3' => 'lca',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇱🇨',
                'full_name' => 'Saint Lucia , St. Lucia',
                'top_level_domain' => '.lc',
            ),
            array (
                'id' => 179,
                'name' => 'Kiribati',
                'calling_code' => '686',
                'capital' => 'South Tarawa',
                'code' => 'ki',
                'code_alpha3' => 'kir',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'emoji' => '🇰🇮',
                'full_name' => 'The Republic of Kiribati',
                'top_level_domain' => '.ki',
            ),
            array (
                'id' => 180,
                'name' => 'Saint Vincent and the Grenadines',
                'calling_code' => '1784',
                'capital' => 'Kingstown',
                'code' => 'vc',
                'code_alpha3' => 'vag',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇻🇨',
                'full_name' => 'Saint Vincent and the Grenadines',
                'top_level_domain' => '.vc',
            ),
            array (
                'id' => 181,
                'name' => 'Tonga',
                'calling_code' => '676',
                'capital' => 'Nuku\'alofa',
                'code' => 'to',
                'code_alpha3' => 'ton',
                'currency_code' => 'TOP',
                'currency_name' => 'Pa’anga',
                'emoji' => '🇹🇴',
                'full_name' => 'The Kingdom of Tonga',
                'top_level_domain' => '.to',
            ),
            array (
                'id' => 182,
                'name' => 'Grenada',
                'calling_code' => '1473',
                'capital' => 'St. George\'s',
                'code' => 'gd',
                'code_alpha3' => 'grd',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇬🇩',
                'full_name' => 'Grenada',
                'top_level_domain' => '.gd',
            ),
            array (
                'id' => 183,
                'name' => 'Antigua and Barbuda',
                'calling_code' => '1268',
                'capital' => 'Saint John\'s',
                'code' => 'ag',
                'code_alpha3' => 'atg',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇦🇬',
                'full_name' => 'Antigua and Barbuda',
                'top_level_domain' => '.ag',
            ),
            array (
                'id' => 184,
                'name' => 'Seychelles',
                'calling_code' => '248',
                'capital' => 'Victoria',
                'code' => 'sc',
                'code_alpha3' => 'syc',
                'currency_code' => 'SCR',
                'currency_name' => 'Seychelles Rupee',
                'emoji' => '🇸🇨',
                'full_name' => 'the Republic of Seychelles',
                'top_level_domain' => '.sc',
            ),
            array (
                'id' => 185,
                'name' => 'Andorra',
                'calling_code' => '376',
                'capital' => 'Andorra la Vella',
                'code' => 'ad',
                'code_alpha3' => 'and',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇦🇩',
                'full_name' => 'The Principality of Andorra',
                'top_level_domain' => '.ad',
            ),
            array (
                'id' => 186,
                'name' => 'Dominica',
                'calling_code' => '1767',
                'capital' => 'Roseau',
                'code' => 'dm',
                'code_alpha3' => 'dma',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇩🇲',
                'full_name' => 'The Commonwealth of Dominica',
                'top_level_domain' => '.dm',
            ),
            array (

                'id' => 187,
                'name' => 'St Kitts-Nevis',
                'calling_code' => '1869',
                'capital' => 'Basseterre',
                'code' => 'kn',
                'code_alpha3' => 'kna',
                'currency_code' => 'XCD',
                'currency_name' => 'East Caribbean Dollar',
                'emoji' => '🇰🇳',
                'full_name' => 'The Federation of Saint Kitts and Nevis',
                'top_level_domain' => '.kn',
            ),
            array (

                'id' => 188,
                'name' => 'Marshall Islands',
                'calling_code' => '692',
                'capital' => 'Majuro',
                'code' => 'mh',
                'code_alpha3' => 'mhl',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇲🇭',
                'full_name' => 'The Republic of Marshall Islands',
                'top_level_domain' => '.mh',
            ),
            array (
                'id' => 189,
                'name' => 'Monaco',
                'calling_code' => '377',
                'capital' => 'Monaco',
                'code' => 'mc',
                'code_alpha3' => 'mco',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇲🇨',
                'full_name' => 'The Principality of Monaco',
                'top_level_domain' => '.mc',
            ),
            array (
                'id' => 190,
                'name' => 'Liechtenstein',
                'calling_code' => '423',
                'capital' => 'Vaduz',
                'code' => 'li',
                'code_alpha3' => 'lie',
                'currency_code' => 'CHF',
                'currency_name' => 'Swiss Franc',
                'emoji' => '🇱🇮',
                'full_name' => 'Principality of Liechtenstein',
                'top_level_domain' => '.li',
            ),
            array (
                'id' => 191,
                'name' => 'San Marino',
                'calling_code' => '378',
                'capital' => 'CityCms of San Marino',
                'code' => 'sm',
                'code_alpha3' => 'smr',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇸🇲',
                'full_name' => 'The Republic of San Marino',
                'top_level_domain' => '.sm',
            ),
            array (
                'id' => 192,
                'name' => 'Palau',
                'calling_code' => '680',
                'capital' => 'Ngerulmud',
                'code' => 'pw',
                'code_alpha3' => 'plw',
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'emoji' => '🇵🇼',
                'full_name' => 'The Republic of Palau',
                'top_level_domain' => '.pw',
            ),
            array (

                'id' => 193,
                'name' => 'Tuvalu',
                'calling_code' => '688',
                'capital' => 'Funafuti',
                'code' => 'tv',
                'code_alpha3' => 'tuv',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'emoji' => '🇹🇻',
                'full_name' => 'Tuvalu',
                'top_level_domain' => '.tv',
            ),
            array (

                'id' => 194,
                'name' => 'Nauru',
                'calling_code' => '674',
                'capital' => 'Yaren',
                'code' => 'nr',
                'code_alpha3' => 'nru',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'emoji' => '🇳🇷',
                'full_name' => 'The Republic of Nauru',
                'top_level_domain' => '.nr',
            ),

            array (
                'id' => 195,
                'name' => 'Vatican CityCms State',
                'calling_code' => '3906698',
                'capital' => 'Vatican CityCms',
                'code' => 'va',
                'code_alpha3' => 'vat',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇻🇦',
                'full_name' => 'Vatican CityCms State',
                'top_level_domain' => '.va',
            ),

            array (
                'id' => 196,
                'name' => 'Kosovo',
                'calling_code' => '383',
                'capital' => 'Pristina',
                'code' => 'xk',
                'code_alpha3' => '',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'emoji' => '🇽🇰',
                'full_name' => 'The Republic of Kosovo',
                'top_level_domain' => '',
            ),

        );

        DB::table('countries')->insert($countries);
    }
}
